apiVersion: v1
kind: Service
metadata:
  name: work-service
spec:
  selector:
    app: math-power
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 443
      targetPort: 3001
